tools:
    external_code_coverage: false
checks:
    php:
        code_rating: true
        duplication: true

filter:
    excluded_paths:

build:
    tests:
        override:
            -
                command: 'vendor/bin/phpunit --coverage-clover=clover.xml'
                coverage:
                    file: 'clover.xml'
                    format: 'clover'